apiVersion: apps/v1
kind: Deployment
metadata:
  name: listapp-backend
  labels:
    app: listapp-backend
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: listapp-backend
  template:
    metadata:
      labels:
        app: listapp-backend
        tier: backend
    spec:
      containers:
        - name: listapp-backend
          image: listapp-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/listapp_db"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: listapp-backend-service
  labels:
    app: listapp-backend
spec:
  selector:
    app: listapp-backend
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  type: ClusterIP
