--The Report (hackerrank)

SELECT 
    IF(GRADE < 8, NULL, NAME),
    G.GRADE,
    MARKS
FROM STUDENTS S
JOIN GRADES G
WHERE S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK
ORDER BY G.GRADE DESC, S.NAME ASC


