//Lineal comment

/*
In this file I will generate a list of users
searched for the ID in the base of data
or searched by mail.
 */

/**
 * The file represent a search of users
 * we have in the system comparing with the 
 * data base
 * 
 */


//Number for all the types of numbers. Integers or floats
console.log(typeof 50.6);

//String chain of text
"Michael Vales";
console.log(typeof "Michael Vales");

//Boolean true, false
console.log(typeof true);

/**
 * Type of data - data collection
 */

/**Objects is a data collection that contains
 * a idenftifier and a value. 
 */

//Array
console.log(["Jose","José","Juan","Jean","Oto"]) ;

//Object
console.log(typeof{
    nombre: "Beto", 
    apellido: "Quiroga"
})

//Null
console.log(typeof null);

/**
 * data type undefined
 */

console.log(typeof undefined);

//statement and assignment
let x = "Beto Quiroga" ;

console.log(x);

/**
 * Assignment of reference
 */
let teacher = "Alexys";
let student = teacher;
console.log(teacher);

/**
 * Constant
 */
const NOMBRE_EMPRESA = "EDTeam";
const SITIO_WEB = "https://ed.team";
